### PR TITLE
Upgrade all deprecated dependencies

### PR DESCRIPTION
**Pull request by jlengrand**
* Upgrades chalk to 4.1.0
* Upgrades cosmiconfig to 7.0.0
* Upgrades uglifyjs-webpack-plugin to 2.2.0
* Upgrades copy-webpack-plugin to 6.2.0
* Upgrades sockjs-client to 1.5.0
* Upgrades optimize-css-assets-webpack-plugin to 5.0.4
* Upgrades assets-webpack-plugin to 5.1.2
* Upgrades workbox-webpack-plugin to 5.1.4
* Upgrades react-error-overlay to 6.0.7
* Upgrades http-proxy-middleware to 1.0.5
* Upgrades fs-extra to 9.0.1
* ~~Upgrades react-dev-utils to 10.2.1~~

closes #322 #510 #454 #460 #507 #506 #473 #457 #444 #429 #421 #404

### CODE REVIEW

**Comment by jlengrand** [comment]
Can you add the hacktoberfest-accepted tag to that PR by any chance @halfzebra ?

**Comment by Slumber86** [comment]
I'm commenting just to point out that `react-dev-utils` is breaking the build, we are tryng to update it for month but is full of breaking changes. @jlengrand please consider to remove the update

**Comment by jlengrand** [comment]
Interesting, thanks for the info! In what way does it break the build? Both CIs pass and I have been running the thing locally without issues? 

Can you give some more context so I can look into it  please?

**Comment by Slumber86** [comment]
It shows a white page  with this errror:

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/ago/progetti/github/create-elm-app/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/ago/progetti/github/create-elm-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ago/progetti/github/create-elm-app/node_modules/express/lib/router/index.js:317:13)
    at /Users/ago/progetti/github/create-elm-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/ago/progetti/github/create-elm-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/ago/progetti/github/create-elm-app/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/ago/progetti/github/create-elm-app/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/ago/progetti/github/create-elm-app/node_modules/express/lib/router/layer.js:95:5)`

just checkout the project and run `npm run app:start`

**Comment by jlengrand** [comment]
Alright @Slumber86 i've reverted the `react-dev-utils` change. 

I see that since I created that PR, 5 more dependencies deprecations came in. If this one does not get merge soon, it will be outdated again. 
I have no problem adding the extra deps in this PR (except for react-dev-utils) but it'd be nice if I could get a signal whether this is desired, welcome or worthful :). 

Thanks for the help BTW!

**Comment by jlengrand** [comment]
Annnnd, the build is green!

**Comment by Slumber86** [comment]
I think we should hear from @halfzebra

**Comment by jlengrand** [comment]
That's alright. I don't want to overload him either :). Is @halfzebra the only current contributor for the project?

**Review by halfzebra — APPROVED** [review]
Merging this, thanks for the effort, and sorry for the delay!

**Pull request merged**
