### PR TITLE
Introduce lerna

### PR DESCRIPTION
**Pull request by halfzebra**
This is the first PR focused on splitting CEA into separate packages #183 

As a first step I'm moving create-elm-app into packages.

### CODE REVIEW

**Comment by fobos** [comment]
Will review it later today

**Comment by halfzebra** [comment]
@fobos please let me know if you will have time to check this one out!

**Comment by fobos** [comment]
Am I right that you going to split CEA into separate packages containing simple command for CEA?
Can you describe what are you going to do with it next?

**Comment by halfzebra** [comment]
@fobos thanks, that's a very good question :slightly_smiling_face: 

Originally I wanted to move `./scripts/utils` into a separate npm package, so ejecting is similar to Create React App, but there's more to it.

I also want to have a reusable `elm-app-scripts`, which will contain the scripts for running the app, which will enable people to customize Create Elm App with less effort.

Having everything isolated, just as in CRA, there might be an opportunity to create a CRA-compatible `elm-app-scripts`, so it's possible to use Elm setup with Create React App(not a very big benefit, but might be a low hanging fruit)

I wanted to keep the semantic release setup, but also add lerna to manage a multi-package repo.

**Comment by fobos** [comment]
@halfzebra thanks for explanation.

**Comment by halfzebra** [comment]
On hold due to [https://github.com/atlassian/lerna-semantic-release/issues/89](https://github.com/atlassian/lerna-semantic-release/issues/89)

**Comment by halfzebra** [comment]
Closing this in favor of adopting https://github.com/Updater/semantic-release-monorepo

**Pull request closed without merging**
