### PR TITLE
Upgrade elm/browser and elm/core

### PR DESCRIPTION
**Pull request by jouderianjr**
- Upgrading elm browser in order to use the new UI for the debugger
- Upgrading elm core to have some bug fixings

### CODE REVIEW

**Comment by JoshuaHall** [comment]
@jouderianjr similarly, `elm/core` was upgraded to `1.0.4` yesterday.

**Comment by jouderianjr** [comment]
@JoshuaHall I've updated the pr, thanks for the suggestion

**Comment by halfzebra** [comment]
Hi Jouderian!

Very nice initiative, thanks for doing this! 👍 

Can change the commit message `chore: upgrade elm/core -> fix: upgrade elm/core`, so semantic release will reflect your change in the changelog?

**Comment by jouderianjr** [comment]
@halfzebra done, sorry about that 💃

**Comment by halfzebra** [comment]
Thanks a lot! 👍

**Pull request merged**
