### PR TITLE
Attempt to keep src folder pure elm

### PR DESCRIPTION
**Pull request by lrosa007**
Simply moved everything that is none elm to a new `public` folder. I had this idea when using `create-alm-app` and felt that it would be nice to keep the `src` folder pure elm.

closes: https://github.com/halfzebra/create-elm-app/issues/123

### CODE REVIEW

**Comment by tbash** [comment]
What would you think about moving the css, js, and that logo into their own dirs? 
maybe something like:
```
  ▾ public/
    ▾ css/
        main.css
    ▾ js/
        index.js # or main.js
    ▾ media/
        logo.svg
    favicon.ico
    index.html
  ▸ src/
  ▸ test/
  .gitignore
  README.md
  elm-package.json
```
cc: @halfzebra

**Comment by lrosa007** [comment]
@tbash I like it

**Comment by halfzebra** [comment]
@lrosa007 sorry for the silence, I'll look into this PR shortly!

**Comment by lrosa007** [comment]
There are some conflicts, I'll rebase and fix that.

**Comment by fobos** [comment]
@lrosa007 could you please resolve conflicts one more time?

**Comment by lrosa007** [comment]
yes @fobos I never totally forgot to do it

**Comment by lrosa007** [comment]
ok @halfzebra & @fobos rebase is done

**Comment by halfzebra** [comment]
@lrosa007 thanks for the rebase, unfortunately we have to continue the discussion about the future structure in #135

Let's keep this PR on hold and merge it when we have a conclusion.

**Comment by lrosa007** [comment]
@halfzebra got it, thanks. 👍

**Comment by halfzebra** [comment]
@lrosa007 Thank you very much for your contribution!

This PR is partially merged in #138

Unfortunately, we can not accept all of the changes, made in this PR.

The reason why `js/` and `css/` folders are still in `src/` is that `public/` folder should serve as a folder for content, which is served outside the module system(i.e. not imported in `index.js`)

During ElmEurope 2017 we have been talking a lot about this specific PR and the options we could consider while reworking the template structure. @eeue56 have shared some experience about that, his opinion is that all the files inside the module system should be located in the same place.

For now, we will use `public/` folder for static content, which is a highly demanded feature! 🙂 

Thank you for initiating and participating in the discussion! 👍 

#135 will be scoped down to smaller discussions, so we don't have to come up with the entire new structure.

Sorry for not accepting the entire list of changes, preserving the original semantics of `public/` folder seems quite important at the moment.

**Comment by lrosa007** [comment]
@halfzebra Thanks 🎉

**Pull request closed without merging**
