### PR TITLE
Add elm-app commands as npm scripts

### PR DESCRIPTION
**Pull request by davesnx**
Hi @halfzebra 

I open this PR to facilitate to call elm-app from outside. (It's similar what create-react-app does).
I change the README only, If it does make sense I would change the CLI messages too.

### CODE REVIEW

**Comment by halfzebra** [comment]
@davesnx Hello and thanks for the PR!

Could you please elaborate a little bit more on the goal of this PR?

**Comment by davesnx** [comment]
Yes @halfzebra 

The idea is that the JavaScript experience with `package.json` is that contains all the interface to build/start/test your application. There a few "hidden" conventions that `**npm start** always mean launch a dev server`, `**npm run build** means compile source files`, etc...

I see that you have elm-app as a internal cli for doing that, the same way as `create-react-app` has `react-scripts`, they have the scripts defined on the `package.json` as well to follow this convention.

It's just a proposal I do not want to force anything. It's just a wrapper around the `elm-app` in npm scripts. Feel free to reject it if you don't feel super comfortable with the changes.

**Comment by davesnx** [comment]
Hey @halfzebra I miss understood how the template works, I was pretty wrong thinking that package.json was the template.

**Comment by halfzebra** [comment]
@davesnx that's alright, Create Elm App tries to avoid putting `package.json` into the template by design.

**Pull request closed without merging**
