### PR TITLE
build(webpack): update webpack to version 2.2.1

### LINKED ISSUE #71: Update to Webpack 2
It's in beta but very stable - I've used it on numerous projects and not had issues; and it's not a huge amount of change.

Would you be happy with a PR if I found the time to make it? :)

### PR DESCRIPTION
**Pull request by Lodin**
This PR closes #71 and provides following changes:
* update webpack to version 2.2.1, 
* update all dependencies to the newest versions, 
* fix es6-es5 mixed style, 
* fix displaying compilation errors

### CODE REVIEW

**Comment by Lodin** [comment]
Looks like elm-webpack-loader does not support node `v4.0.0`, it requires `>=v6.0.0`:
```sh
error elm-webpack-loader@4.2.0: The engine "node" is incompatible with this module. Expected version ">=6.0.0".
```

**Comment by Lodin** [comment]
Error in the `node v7` branch seems to be like an error in `npm v4.1.2` itself. It is connected to the `prune` command of npm. I created an [issue](https://github.com/npm/npm/issues/15646) at the npm page. It might be a workaround to temporarily disable this command in travis.

**Comment by Lodin** [comment]
Have updated node version to `v6.0.0` due to `elm-webpack-loader` dependency.

**Comment by Lodin** [comment]
Any updates on this?

**Comment by halfzebra** [comment]
@Lodin great job!

Finally I have some free time to look in to this. Will be merging asap!

**Pull request merged**
