### PR TITLE
Update insecure dependencies

### PR DESCRIPTION
**Pull request by afriestad**
I ran `npm audit` on the current master, and got the following output:

```
create-elm-app$ npm i && npm i --package-lock-only && npm audit

[...]

added 274 packages from 176 contributors, removed 22 packages, updated 13 packages and audited 33377 packages in 23.756s
found 9 vulnerabilities (1 low, 1 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN deprecated fsevents@1.2.4: Way too old
npm notice created a lockfile as package-lock.json. You should commit this file.
added 67 packages from 25 contributors and audited 33377 packages in 11.444s
found 9 vulnerabilities (1 low, 1 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install http-proxy-middleware@0.20.0  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ http-proxy-middleware                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ http-proxy-middleware > micromatch > braces                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install css-loader@3.2.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ css-loader                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ css-loader > cssnano > postcss-svgo > svgo > js-yaml         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/788                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ css-loader                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ css-loader > cssnano > postcss-svgo > svgo > js-yaml         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/813                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm-test                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm-test > fsevents > node-pre-gyp > tar                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm-test                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm-test > lodash                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm-test                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm-test > node-elm-compiler > find-elm-dependencies >       │
│               │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 1fb45c857a90c84bab03ccb5bed8abdd0003ac7a7f40c9e8b14bb021ad0… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 1fb45c857a90c84bab03ccb5bed8abdd0003ac7a7f40c9e8b14bb021ad0… │
│               │ > node-elm-compiler > find-elm-dependencies > lodash         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm-test                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm-test > node-elm-compiler > lodash                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 1fb45c857a90c84bab03ccb5bed8abdd0003ac7a7f40c9e8b14bb021ad0… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 1fb45c857a90c84bab03ccb5bed8abdd0003ac7a7f40c9e8b14bb021ad0… │
│               │ > node-elm-compiler > lodash                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 9 vulnerabilities (1 low, 1 moderate, 7 high) in 33377 scanned packages
  run `npm audit fix` to fix 1 of them.
  2 vulnerabilities require semver-major dependency updates.
  6 vulnerabilities require manual review. See the full report for details.
```

As you can see, there are some quite severe vulnerabilities present here, including denial of service, arbitrary code execution and arbitrary file overwrites.

This PR fixes the denial of service vulnerabilities and the arbitrary code execution vulnerability. It does not fix the vulnerabilities present in `elm-test`, as no update is currently available. However https://github.com/rtfeldman/node-test-runner/issues/360 suggests that a new release which fixes all these vulnerabilities is just around the corner.

The update of `http-proxy-middleware` from `0.17.4` to `0.20.0` was unproblematic.

The update of `css-loader` from `0.28.9` to `3.2.0` was slightly more problematic. Specifically, the `minimize` option was removed in [css-loader release 1.0.0](https://github.com/webpack-contrib/css-loader/releases/tag/v1.0.0); quoth the release notes:

>remove minimize option, use postcss-loader with cssnano or use optimize-cssnano-plugin plugin

I am not quite comfortable with webpack configs yet, so I have not done this change. Presumably, this currently means that running `npm build` on an ejected project (and perhaps also on non-ejected projects?) will no longer minimize css.

I am sure re-adding this functionality will be both easy and quick for someone who is more experienced with webpack than I am, and so I would appreciate pointers or help with doing so.

### CODE REVIEW

**Comment by halfzebra** [comment]
Hi Andreas!

Thanks for looking into this, I appreciate the explanation of the changes you've made :+1: 

I think it would make sense to provide users with some means to optimize CSS assets. We could use [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) with a similar setup to [Create React App.](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L255)

What do you think?

**Comment by halfzebra** [comment]
Sorry for the delay, I think it would make sense to add it in this PR since it removes the old way of minimizing CSS assets.

Please let me know if I can assist in any way!

**Comment by afriestad** [comment]
@halfzebra I have now tried to add it. I more or less verbatim copied the entry from create-react-app, and it seems to be working in all stages of the projects. Tests are also passing.

It might still be worth double checking this by building a test app yourself, since I am not 100% sure of what I am doing.

**Comment by halfzebra** [comment]
Nice job! :+1: 

I'll merge this in, there's a minor issue with `browserlist` deprecation warning, but I think this is something we can live with for now.

**Pull request merged**
