### PR TITLE
fix(index.js): Fix running application

### LINKED ISSUE #114: New apps broken: Cannot read property 'embed' of undefined
I was getting this error in Chrome after creating a new app and running `elm-app start`:
`Uncaught TypeError: Cannot read property 'embed' of undefined`

It appears that due to some name changes, `Elm.Main.embed(root, logoPath)` should now be `Elm.App.embed(root, logoPath)`: https://github.com/halfzebra/create-elm-app/blob/master/template/src/index.js#L7

### PR DESCRIPTION
**Pull request by fobos**
Forgot to rename main module name in index.js during refactoring #110

Closes #114

### CODE REVIEW

**Comment by halfzebra** [comment]
@fobos thanks for the fix! 👍

**Comment by fobos** [comment]
@halfzebra no problem. But I trying to understand what's went wrong when I tested after refactoring... 😰

**Comment by halfzebra** [comment]
@fobos there should have been an e2e test to check if the app is working in the browser.

In fact, I have had it written and I was just too busy to push it 😢

**Comment by fobos** [comment]
@halfzebra I think about e2e today.
It would be great to have it as part of CI.

**Pull request merged**
