### PR TITLE
chore: upgrade Elm to version 0.19.1

### PR DESCRIPTION
**Pull request by olpeh**
Hi. I tried upgrading my hobby project that uses create-elm-app to Elm version 0.19.1. 

It does not seem to be possible without upgrading the Elm version in create-elm-app (?). 

So, here's a PR that does that.

### CODE REVIEW

**Comment by halfzebra** [comment]
Hi Olavi!

Thanks for working on this PR! :+1: 

It seems like the NPM package is broken at the moment, so we'll have to wait until it is fixed.

**Comment by olpeh** [comment]
Oh, I see. There's also `0.19.1-2` available now. I'll try with that and see if that helps.

**Comment by runarfu** [comment]
I didn't see this PR for some reason and opened https://github.com/halfzebra/create-elm-app/pull/378. Feel free to close either.

**Comment by optikfluffel** [comment]
@olpeh I've seen elm-test `0.19.1-1` used over at [simonh1000/elm-webpack-starter#31](https://github.com/simonh1000/elm-webpack-starter/pull/31/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R31), although I don't see this version on npm 🤔

**Comment by andys8** [comment]
I think it's either latest tag `elm@latest-0.19.1` or the latest version which is currently release `0.19.1-3`

**Comment by halfzebra** [comment]
Hi Olavi!

It looks like the upgrade is almost done. :crossed_fingers: 
I've opened a PR towards your branch with a fix for the failing tests. https://github.com/olpeh/create-elm-app/pull/1

I think merging it would be enough to make this green and then it will be automatically released.

**Comment by olpeh** [comment]
Thanks @halfzebra :tada:

**Pull request merged**
